name: 'Run Loadmill Test Plan'
description: 'Run a Loadmill test plan'
inputs:
  id:
    description: 'Test Plan Id'
    required: true
  token:
    description: 'User token to run the test plan on behalf of'
    required: true
  additionalDescription:
    description: 'Added at the end of the test plan run description (e.g. build number)'
    required: false
  labels:
    description: 'Execute flows that are assigned to a specific label (e.g. "label1,label2")'
    required: false
  labelsExpression:
    description: 'Execute flows that match the labels expression. An expression may contain the characters ( ) & | ! (e.g. "(label1 | label2) & !label3\")'
    required: false
  parallel:
    description: 'Set the concurrency amount of running test suites in a test plan. Max concurrency is 10.'
    required: false
  pool:
    description: "Execute tests from a dedicated agent's pool (when using private agent)"
    required: false
  parameters:
    description: 'Override pre-defined parameter values via command line arguments by passing name=value pairs seperated by comma  (e.g. "name=value,name2=value2")'
    required: false
  branch:
    description: "Run the test plan's suites from a Git branch"
    required: false
outputs:
  result:
    description: 'The result of the test plan run'
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: 'check'
  color: 'blue'